name: "Build Dev Container"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cd hello-api
            dotnet build
            dotnet run
